apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwarrk-back
  namespace: test-cicd  # 배포할 네임스페이스를 test-cicd로 설정
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwarrk-back
  template:
    metadata:
      labels:
        app: hwarrk-back
    spec:
      containers:
        - name: hwarrk-back
          image: 904233101802.dkr.ecr.ap-northeast-2.amazonaws.com/hwarrk-back/dev:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hwarrk-back-service
  namespace: test-cicd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:904233101802:certificate/f45db805-9007-450b-bec9-3532a0baa700"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: hwarrk-back